# Generated by Django 5.0.1 on 2024-06-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(max_length=2)),
                ('roomno', models.CharField(max_length=4, unique=True)),
                ('roomtype', models.CharField(max_length=15)),
            ],
        ),
    ]
