# Generated by Django 5.0.1 on 2024-06-27 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('dept', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cleaningstaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('shift', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hme.ward')),
            ],
        ),
        migrations.CreateModel(
            name='Inpatients',
            fields=[
                ('patientid', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('phn', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=3)),
                ('admsndate', models.DateField()),
                ('bystander', models.CharField(max_length=40)),
                ('doct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hme.doctor')),
                ('roomno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hme.ward')),
            ],
        ),
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dischargedate', models.DateField()),
                ('time', models.TimeField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hme.inpatients')),
            ],
        ),
        migrations.CreateModel(
            name='Careplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.TextField()),
                ('diagnosis', models.TextField()),
                ('inference', models.TextField()),
                ('planning', models.TextField()),
                ('intervention', models.TextField()),
                ('rationale', models.TextField()),
                ('evaluation', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hme.inpatients')),
            ],
        ),
        migrations.CreateModel(
            name='Newborn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=6)),
                ('time', models.DateField()),
                ('weight', models.CharField(max_length=6)),
                ('blood', models.CharField(max_length=4)),
                ('type', models.CharField(max_length=15)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hme.inpatients')),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('shift', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hme.ward')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transto', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('mode', models.CharField(max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hme.inpatients')),
            ],
        ),
    ]
