# Generated by Django 5.0.1 on 2024-06-28 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hme', '0002_doctor_cleaningstaff_inpatients_discharge_careplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newborn',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
