# Generated by Django 5.0.1 on 2024-06-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hme', '0003_newborn_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newborn',
            name='ampm',
            field=models.CharField(default='AM', max_length=4),
        ),
        migrations.AlterField(
            model_name='newborn',
            name='time',
            field=models.TimeField(),
        ),
    ]
