# Generated by Django 5.0.1 on 2024-06-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hme', '0004_newborn_ampm_alter_newborn_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpatients',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
