# Generated by Django 5.0.1 on 2024-07-01 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hme', '0005_inpatients_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpatients',
            name='roomno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hme.ward'),
        ),
    ]
